name: Release Drafter

on:
  push:
    # Branches to consider in the event; optional, defaults to all.
    # Most commonly, you'll want this to run on pushes to your main branch.
    branches:
      - main # or master, or your default branch
  # The pull_request event is required for the autolabeler feature.
  # If you want the autolabeler to work with PRs from forks, use pull_request_target.
  pull_request:
    types: [opened, reopened, synchronize]
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read # Default permission

jobs:
  update_release_draft:
    # Permissions required by release-drafter
    permissions:
      contents: write          # Required to create a GitHub release
      pull-requests: write     # Required for autolabeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      # (Optional) If you are using GitHub Enterprise, set the GHE_HOST
      # - name: Set GHE_HOST
      #   run: |
      #     echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # This step runs the Release Drafter action.
      - uses: release-drafter/release-drafter@v6 # It's good practice to use a specific version tag
        # (Optional) You can specify a different configuration file name.
        # with:
        #   config-name: my-custom-config.yml
        #   disable-autolabeler: true # Set to true to disable the autolabeler feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}